### ISSUE TITLE
Not importing all content

### ISSUE THREAD

**Issue by ursbraem** [websedit/we_dam2fal62#2]
Hi

I've tried to run the extension, and ran into an issue
I've launched the recommended scheduler task a few times (how can you see if it's completed)?

Then, we_dam2fal62 says in the tab "DAM data":

DAM dataimport
Progress:
855 of 875 data imported to FAL.
Submit

No matter how many times I click submit, it never gets ahead further.
How could I debug this?
And, is it correct to assume that we_dam2fal62 is more powerful than dam_falmigration?
Thanks
Urs

**Comment by ursbraem** [comment]
I've printed txDamEntriesNotImported from DamfalfileController.php - all missing files have umlauts or accents (é) in the filename. [SYS][UTF8filesystem]  is set to true though.

**Comment by websedit** [comment]
You are right. Umlauts cause problems. Right now there is no bugfix for this.
